title: rodrigo.ghed.in
description: O jardim digital de Rodrigo Ghedin
url: "https://rodrigo.ghed.in"
author: Rodrigo Ghedin

excerpt_separator: "\n\n"

markdown: kramdown

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title'

permalink: /blog/:slug
timezone: UTCâˆ’03:00
future: false

exclude:
  - README.md
  - LICENSE.*
  - favicon.ico
  - apple-touch-icon*.png

Blog: /blog